### ISSUE TITLE
Move repository to a new location

### ISSUE THREAD

**Issue by mdom** [jointwt/we-are-twtxt#63]
@prologic I haven't use twtxt for some time now, so it probably makes sense to transfer this repository somewhere else? Maybe to a twtxt origanisation?

**Comment by prologic** [comment]
Feel free to transfer it to the jointwt org 👍

**Comment by mdom** [comment]
I don't have the necessary permission.

**Comment by prologic** [comment]
Do I have to add you to the org first?

**Comment by prologic** [comment]
Or if you just transfer it to me will that work? r￼

**Comment by mdom** [comment]
On Tue, Nov 10, 2020 at 03:09:39AM -0800, James Mills wrote:
> Or if you just transfer it to me will that work? r￼

You can either give me access to the organization (and later revoke it)
or you need to delete your own fork of we-are-twtxt. Otherwise i can't
transfer control.

Cheers, Mario

**Comment by prologic** [comment]
> or you need to delete your own fork of we-are-twtxt. Otherwise i can't
transfer control.

Done.

**Comment by mdom** [comment]
Okay, i transfered the repository. You should now be asked to accept the transfer.

**Comment by prologic** [comment]
Ack, Done!

**Comment by prologic** [comment]
Received! Thank you! 🙇‍♂️ Last thing, do you have the tooling that generates the `we-are-twtxt` and `we-are-bots` feeds from this repo? I'd like to do something with those if I can 🤔

**Comment by kseistrup** [comment]
@prologic I'm the one who ran the "We Are"-scripts. I'll see if can can find some time to make them available to you.

**Comment by prologic** [comment]
Thank you!

**Comment by prologic** [comment]
@kseistrup @mdom I _think_ I got a little confused. One of you is/has leaving/left Twtxt (I believe that's you @mdom ) whilst the other has automated feeds. Who owns/runs/manages the @tiktok @we-are-twtxt @we-ware-bots @moon @beyond and @ddate feeds? 🤔

**Comment by mdom** [comment]
I don't have any bots running that i know of :)

**Comment by kseistrup** [comment]
@prologic I run/ran all feeds that live/lived on enotty.dk, so that'd be me.

**Comment by prologic** [comment]
> I don't have any bots running that i know of :)

Right 😀 Thanks for the clarification!

**Comment by prologic** [comment]
> @prologic I run/ran all feeds that live/lived on enotty.dk, so that'd be me. And I am also the one who has left twtxt.

I see... 🤣 So... Why is it that @mdom was the one that gave up and transferred the repo to me? 😳

I'm so confused! But it's okay 👍

In any case as per above, I'd love it if I could borrow from, use directly or whatever the tooling/software behind these bots, especially @tiktok, @moon, @we-are-twtxt and @we-are-bots (Please) 😀

**Comment by mdom** [comment]
On Thu, Nov 12, 2020 at 12:29:59AM -0800, James Mills wrote:
> > @prologic I run/ran all feeds that live/lived on enotty.dk, so
> > that'd be me. And I am also the one who has left twtxt.
> 
> I see... 🤣 So... Why is it that @mdom was the one that gave up and 
> transferred the repo to me? 😳 I'm so confused! But it's okay 👍  

We are both leaving twtxt. I started the repository, but @kseistrup
helped me manage it. He used the data to run his bots.

Cheers, Mario

**Comment by prologic** [comment]
Ahhhh! Now it all makes perfect sense! Thanks Mario!

**Comment by kseistrup** [comment]
@prologic I already sent you links to gists with the python code I used for @tiktok and @moon. I believe they're attached to your comment on the commit where @kas and @kasdk were being removed from We Are Twtxt.

**Comment by prologic** [comment]
> @prologic I already sent you links to gists with the python code I used for @tiktok and @moon. I believe they're attached to your comment on the commit where @kas and @kasdk were being removed from We Are Twtxt.

Yup got those thanks! 🙇‍♂️
